### ISSUE TITLE
Replace Atom as text editor suggestion

### ISSUE THREAD

**Issue by hadro** [IIIF/training#156]
I don't necessarily know what to replace it with, but Github is removing support for Atom as a standalone text editor, so we should probably find a replacement.

I like Sublime Text, though they do eventually ask you to pay for a licensed version (though you can keep using the free one if you ignore the prompts). It works for linux, mac, and PC, but I admit I haven't done an environmental scan on all the options out there recently.

**Comment by jronallo** [comment]
I used to use Atom and now I use VSCode.

**Comment by glenrobson** [comment]
Training updated to use VSCode.
